---
title: "DEG"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(error = F)
knitr::opts_chunk$set(fig.width = 8)

library(Seurat)
library(cowplot)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(enrichR)
library(fgsea)
library(data.table)
#library(EnhancedVolcano)
  
```


# Set working dir

```{r,,eval=T,message=F,warning=F,error=F}

here::i_am("3_deg.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r}
source("../_common/functions.R")
combined <- qs::qread('./combined.qsave')

# To obtain all_gene_sets, please run msigdb
# install.packages("msigdbr")
# library(msigdbr)
all_gene_sets = msigdbr(species = "Homo sapiens")
# all_gene_sets <- qs::qread("../RNAseq_workflow/all_gene_sets_human.qsave")

DefaultAssay(combined) <- "RNA"

dbs <-
  c(
    "GO_Molecular_Function_2023",
    "GO_Cellular_Component_2023",
    "GO_Biological_Process_2023",
    "KEGG_2021_Human"
  )

dir.create('./result')
dir.create('./result/deg')

```

# DEG, stimulation vs control


```{r}

  # Create new directories to store results
  dir.create(paste0("../result/deg"))
  # Define the result directory path 
  RESULT_DIR <- paste0("../result/deg", "/")
  
  # Set the ident to the sample in the combined data
  Idents(combined) <- combined$orig.ident
  # Subset the data for the control and stim samples
  combined <- subset(combined, ident = c(paste0("ctrl_raw_feature_bc_matrix"), paste0("stim_raw_feature_bc_matrix")))
  
  # Get cell types in the current combined data
  this_cell_type <- levels(as.factor(combined$cell_type))
  
  i = 1
  for (i in seq_along(this_cell_type)) {
    # Set cell type for the current iteration
    this_ct <- this_cell_type[i]
    # Set the identity to the cell_type in the combined object
    Idents(combined) <- combined$cell_type
    # Subset the combined data based on the current cell type
    this_combined <- subset(combined, ident = this_ct)
    
    # Set the identity to the sample in the this_combined object
    Idents(this_combined) <- this_combined$orig.ident
    # Set the default assay in this_combined object to "RNA"
    DefaultAssay(this_combined) <- "RNA"
    
    # Checks if two different samples are there in the dataset and each sample has more than 3 cells
    check_analysis <- length(which(as.numeric(table(
      this_combined$orig.ident
    )) > 0)) == 2 & length(which(as.numeric((
      table(this_combined$orig.ident)
    ) > 3) > 0)) == 2
    
    # Confirm both samples have same cell type
    if (check_analysis) {
      
      # fgsea enrichment
      this_combined[["RNA"]] <- JoinLayers(this_combined[["RNA"]])
      cts_fc <- FoldChange(this_combined,
                           ident.1 = paste0("stim_raw_feature_bc_matrix"),
                           ident.2 = paste0("ctrl_raw_feature_bc_matrix"))
      
      res_gsea <- cts_fc %>%
        rownames_to_column("gene") %>%
        dplyr::select(gene, avg_log2FC) %>%
        arrange(desc(avg_log2FC)) %>%
        na.omit() %>%
        distinct() %>%
        group_by(gene) %>%
        deframe() %>%
        sort(decreasing = T)
      
      # GOBP
      this_terms <- all_gene_sets %>%
        filter(gs_collection == 'C5' & gs_collection == 'GO:BP')
      
      m_list = this_terms %>% split(x = .$gene_symbol, f = .$gs_name)
      
      fgseaRes <- fgsea(pathways = m_list,
                        stats = res_gsea)
      
      fgseaResTidy <- fgseaRes %>%
        as_tibble() %>%
        dplyr::filter(padj < 0.05) %>%
        arrange(desc(NES)) %>%
        dplyr::select(-ES) %>%
        arrange(padj, desc(NES))
      
      fwrite(
        fgseaResTidy,
        file = paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GSEA_GOBP.csv"),
        sep = ",",
        sep2 = c("", " ", "")
      )
      
      # GSEA KEGG
      this_terms <- all_gene_sets %>%
        filter(gs_collection == 'C2' & gs_collection %in% c('CP:KEGG_LEGACY', 'CP:KEGG_MEDICUS'))
      
      m_list = this_terms %>% split(x = .$gene_symbol, f = .$gs_name)
      
      fgseaRes <- fgsea(pathways = m_list,
                        stats = res_gsea)
      
      fgseaResTidy <- fgseaRes %>%
        as_tibble() %>%
        dplyr::filter(padj < 0.1) %>%
        arrange(desc(NES)) %>%
        dplyr::select(-ES) %>%
        arrange(padj, desc(NES))
      
      fwrite(
        fgseaResTidy,
        file = paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GSEA_KEGG.csv"),
        sep = ",",
        sep2 = c("", " ", "")
      )
      
      # DEG
      cts_markers <-
        FindMarkers(
          this_combined,
          ident.1 = paste0("stim_raw_feature_bc_matrix"),
          ident.2 = paste0("ctrl_raw_feature_bc_matrix")
        ) %>%
        rownames_to_column("gene") %>%
        filter(p_val_adj < 0.05)
      
      avg_expr_deg <-
        AverageExpression(this_combined, features = cts_markers$gene)$RNA %>%
        as.data.frame() %>%
        rownames_to_column("gene")
      
      cts_markers <- cts_markers %>%
        left_join(avg_expr_deg, by = "gene") %>%
        arrange(desc(avg_log2FC))
      
      cts_markers %>%
        write_csv(paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl.csv"))
      
      this_up <- cts_markers %>%
        filter(avg_log2FC > 0) %>%
        pull(gene)
      this_down <- cts_markers %>%
        filter(avg_log2FC < 0) %>%
        pull(gene)
      
      # filter DEG
      if (length(this_up) > 10 &
          length(this_down) > 10) {
        top_up <- cts_markers %>%
          top_n(10, avg_log2FC) %>%
          pull(gene)
        top_down <- cts_markers %>%
          top_n(-10, avg_log2FC) %>%
          pull(gene)
        
        
        ### Enrichr: UP
        if (length(this_up) > 10) {
          enriched_combined <- enrichr(this_up, dbs)
          enriched_combined <- lapply(enriched_combined, function(x) {
            x$Overlap <- paste0(" ", x$Overlap)
            return(x[, c(-5, -6)])
          })
          
          write.csv(
            enriched_combined$GO_Molecular_Function_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_MF_up.csv")
          )
          write.csv(
            enriched_combined$GO_Cellular_Component_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_CC_up.csv")
          )
          write.csv(
            enriched_combined$GO_Biological_Process_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_BP_up.csv")
          )
          write.csv(
            enriched_combined$KEGG_2021_Human,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_KEGG_up.csv")
          )
        }
        Sys.sleep(3)
         ### Enrichr: DOWN
        if (length(this_down) > 10) {
          enriched_combined <- enrichr(this_down, dbs)
          enriched_combined <- lapply(enriched_combined, function(x) {
            x$Overlap <- paste0(" ", x$Overlap)
            return(x[, c(-5, -6)])
          })
          
          write.csv(
            enriched_combined$GO_Molecular_Function_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_MF_down.csv")
          )
          write.csv(
            enriched_combined$GO_Cellular_Component_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_CC_down.csv")
          )
          write.csv(
            enriched_combined$GO_Biological_Process_2023,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_GO_BP_down.csv")
          )
          write.csv(
            enriched_combined$KEGG_2021_Human,
            paste0(RESULT_DIR, this_ct, "_Stim_vs_Ctrl_KEGG_down.csv")
          )
        }
      }
    }
  }

```

