---
title: Trajectory analysis using Monocle
author: "Megan McNutt"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: false
    number_sections: true
    code_folding: hide
---

<style>
    body .main-container {
        max-width: 90%;
        width: 90%;
    }
</style>

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(here)
library(qs)
library(tidyverse)
library(Seurat)
library(SeuratDisk)
library(monocle3)
library(SeuratWrappers)
library(patchwork)
#library(dplyr)


```

# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("../common/functions.R")
here::i_am("4_trajectory.rmd")
print(paste("Current working directory:", here::here()))

```

```{r,echo=F,eval=T,message=F,warning=F,error=F}
set.seed(42)

combined <- qs::qread(paste0("combined.qsave"))

```

# Set Colorblind-friendly palettes
```{r}

tol_high_contrast_palette <- c("#DDAA33", "#BB5566", "#004488")
tol_vibrant_palette <- c("#0077BB", "#33BBEE", "#009988",
                         "#EE7733", "#CC3311", "#EE3377",
                         "#BBBBBB")
tol_muted_palette <- c("#332288", "#88CCEE", "#44AA99",
                       "#117733", "#999933", "#DDCC77",
                       "#CC6677", "#882255", "#AA4499")

```

# Setting up monocle3 cell_data_set object using SeuratWrappers
```{r}
cds <- as.cell_data_set(combined)
cds <- cluster_cells(cds, resolution=1e-3)

p1 <- plot_cells(cds, color_cells_by = "cell_type", show_trajectory_graph = FALSE)
p2 <- plot_cells(cds, color_cells_by = "partition", show_trajectory_graph = FALSE)
wrap_plots(p1, p2)

# subsetting partitions
integrated.sub <- subset(as.Seurat(cds, assay = NULL), monocle3_partitions == 1)
cds <- as.cell_data_set(integrated.sub)

```

# Trajectory Analysis
```{r}
cds <- learn_graph(cds, use_partition = TRUE, verbose = FALSE)

plot_cells(cds,
           color_cells_by = "cluster",
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE)
```

# Color cells by pseudotime
```{r}
cds <- order_cells(cds, root_cells = colnames(cds[,clusters(cds) == 4]))
plot_cells(cds,
           color_cells_by = "pseudotime",
           group_cells_by = "cluster",
           label_cell_groups = FALSE,
           label_groups_by_cluster=FALSE,
           label_leaves=FALSE,
           label_branch_points=FALSE,
           label_roots = FALSE,
           trajectory_graph_color = "grey60")

integrated.sub <- as.Seurat(cds, assay = NULL)
FeaturePlot(integrated.sub, "monocle3_pseudotime")
```




# Session info

```{r,echo=F,eval=T,message=F,warning=F}
sessionInfo()
```
