### Single-cell RNA-seq

- [General workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_general_workflow)
- [10x Flex preprocessing](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_10x_Flex_preprocessing)
- [Trajectory analysis](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_trajectory_Slingshot)
- [Cell-cell communication](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_CellCellCommunication_branch)
- [HPV branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_HPV_branch)
- [Seurat to Scanpy](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_Seurat_to_Scanpy)
- [Stomach branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_stomach_branch)
- [ShinyCell portal](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_ShinyCell_portal)
- [Large dataset analysis](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_Sketch_LargeData)
- [Module enrichment](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_module_enrichment)
- [iPSC branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_iPSC_branch)
- [Immune branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_immune_branch)
- [inferCNV](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_inferCNV)
- [Label transfer](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scRNAseq_label_transfer_branch)

### Single-cell ATAC-seq

- [General workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_general_workflow)
- [ArchR branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_ArchR_branch)
- [Cicero branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_cicero_branch)
- [cisTopic branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_cisTopic_branch)
- [ChromVAR motif activity](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_ChromVAR_motif)
- [Gene activity score](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scATACseq_Gene_activity)

### Single-cell Multi-omics

- [AD branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scMultiome_AD_branch)

### Single-cell TCR-seq

- [TCR-seq analysis](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/scTCRseq_analysis)

### Spatial Transcriptomics

- [General workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ST_general_workflow)
- [BayesSpace branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ST_BayesSpace_branch)
- [Giotto branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ST_giotto_branch)
- [Spotlight branch](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ST_spotlight_branch)
- [Cellular neighborhood](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Spatial_Cellular_neighborhood)

### Bulk RNA-seq / ATAC-seq / ChIP-seq

- [RNA-seq workflow pilot](rnaseq-workflow.qmd)
- [RNA-seq nf-core workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/RNAseq_nfcore_workflow)
- [ATAC-seq nf-core workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ATACseq_preprocessing)
- [Bulk ATAC workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Bulk_ATAC_general_workflow)
- [ChIP-seq workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ChipSeq_general_workflow)
- [ChIP-seq workflow v2](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ChipSeq_general_workflow_v2)
- [HOMER motif analysis](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/ChipSeq_HOMER_motif)

### Bisulfite sequencing

- [Bismark aligner](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/BSseq_Bismark_Aligner)

### Whole Genome Sequencing

- [Low-pass karyotyping](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/WGS_Lowpass_karyotyping)

### Gene Regulatory Networks

- [CellOracle workflow](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/GRN_CellOracle)

### Enrichment / downstream analysis

- [Pathway enrichment](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Analysis_Pathway_enrichment)

### Data utilities

- [GEO download](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Data_GEO_download)
- [GEO submission](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Data_GEO_submission)
- [H5AD conversion](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Data_H5AD_conversion)
- [SRA download](https://github.com/OSU-BMBL/BMBL-analysis-notebooks/tree/master/Data_SRA_download)
