---
title: "Cell proportion"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(dittoSeq)
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("6_cell_proportion.Rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")

combined <- qs::qread('combined.qsave')

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$orig.ident

custom_color <-
  as.character(palette36.colors(36)[-2])
two_color <- c('#C0C0C0', '#B00D23')

dir.create('../result')
dir.create('../result/cell_proportion')
```

# cell proportion: barplot

```{r,echo=F,eval=F,message=FALSE,warning=F}
days <- c("0", "2", "5", "10", "14", "30")

day <- "30"

for (day in days) {
  Idents(combined) <- combined$orig.ident
  this_combined <-
    subset(combined, ident = c(paste0("Con", day), paste0("N1KO", day)))
  Idents(this_combined) <- this_combined$cell_type
  
  p1 <-
    dittoBarPlot(
      this_combined,
      "cell_type",
      group.by = "orig.ident",
      xlab = "Sample",
      scale = "percent",
      main = '',
      color.panel = custom_color
    )
  png(
    paste0('../result/cell_proportion/', day, "_proportion_pct.png"),
    width = 2000,
    height = 2000,
    res = 300
  )
  print(p1)
  dev.off()
  
  #p2 <-
  #  dittoBarPlot(
  #    this_combined,
  #    "cell_type",
  #    group.by = "orig.ident",
  #    xlab = "Sample",
  #    scale = "count",
  #    main = '',
  #    color.panel = custom_color
  #  )
  #png(
  #  paste0('../result/cell_proportion/', day, "_proportion_count.png"),
  #  width = 2000,
  #  height = 2000,
  #  res = 300
  #)
  #print(p2)
  #dev.off()
}




```


# cell proportion: pie

```{r,echo=F,eval=F,message=FALSE,warning=F}

this_sample_name <- "N1KO30"

for (this_sample_name in levels(combined$orig.ident)) {
  Idents(combined) <- combined$orig.ident
  this_combined <-
    subset(combined, ident = this_sample_name)
  Idents(this_combined) <- this_combined$cell_type
  
  
  pie_df <- table(as.factor(this_combined$cell_type))
  pct <- round(100 * pie_df / sum(pie_df))
  
  
  png(
    paste0('../result/cell_proportion/', this_sample_name, "_pie.png"),
    width = 3000,
    height = 2000,
    res = 300
  )
  print(pie(
    pie_df,
    labels = paste(names(pie_df), sep = " ", pct, "%"),
    col = custom_color
  ))
  dev.off()
  
}




```



```{r,echo=F,eval=F,message=FALSE,warning=F}
dir.create('result')
dir.create('result/cell_proportion')

Idents(combined) <- combined$orig.ident

Idents(combined) <- combined$empty_category
DefaultAssay(combined) <- "RNA"
i = 14
j = 1
k = 1
for (i in seq_along(levels(provided_marker$cell_type))) {
  this_ct <- levels(provided_marker$cell_type)[i]
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  this_data <- FetchData(object = combined, vars = this_markers)
  selected_cells <- rownames(this_data)
  for (k in seq_along(this_markers)) {
    if (this_direction[k] == "pos") {
      this_cells <- this_data %>%
        filter(get(this_markers[k]) >  0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    } else{
      this_cells <- this_data %>%
        filter(get(this_markers[k]) <= 0) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    }
  }
  
  selected_cells <- unique(selected_cells)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           "positive",
           "negative")
  library(tidyverse)
  
  Idents(combined) <- combined$tmp_ct
  custom_color <- c('#C0C0C0', '#B00D23')
  
  # pct proportion
  p1 <-
    dittoBarPlot(
      combined,
      "tmp_ct",
      group.by = "orig.ident",
      xlab = "Sample",
      scale = "percent",
      main = '',
      color.panel =  c('#C0C0C0', '#B00D23'),
      x.reorder = c(1, 4, 6, 2, 3, 5, 7, 10, 12, 8, 9, 11)
    )
  
  png(
    paste0('result/cell_proportion/', this_ct, "_proportion_pct.png"),
    width = 2000,
    height = 2000,
    res = 300
  )
  print(p1)
  dev.off()

  p2 <-
    dittoBarPlot(
      combined,
      "tmp_ct",
      group.by = "orig.ident",
      xlab = "Sample",
      scale = "count",
      main = '',
      color.panel =  c('#C0C0C0', '#B00D23'),
      x.reorder = c(1, 4, 6, 2, 3, 5, 7, 10, 12, 8, 9, 11)
    )
  
  png(
    paste0('result/cell_proportion/', this_ct, "_proportion_count.png"),
    width = 2000,
    height = 2000,
    res = 300
  )
  print(p2)
  dev.off()
}
```



# Heatmap


```{r}
library(Seurat)
library(cowplot)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
#library(ComplexHeatmap)
library(circlize)

i = 1
j = 1
k = 1
combined@meta.data$tmp_ct <- "other"
for (i in seq_along(levels(provided_marker$cell_type))) {
  this_ct <- levels(provided_marker$cell_type)[i]
  this_markers <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(gene)
  this_direction <- provided_marker %>%
    filter(cell_type == this_ct) %>%
    pull(direction)
  this_data <- FetchData(object = combined, vars = this_markers)
  selected_cells <- rownames(this_data)
  for (k in seq_along(this_markers)) {
    if (this_direction[k] == "pos") {
      this_cells <- this_data %>%
        filter(get(this_markers[k]) >  0.1) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    } else{
      this_cells <- this_data %>%
        filter(get(this_markers[k]) <= 0) %>%
        rownames_to_column("cell") %>%
        pull(cell)
      selected_cells <- intersect(selected_cells, this_cells)
    }
  }
  
  selected_cells <- unique(selected_cells)
  this_obj <- combined[, selected_cells]
  
  combined@meta.data$tmp_ct <-
    ifelse(rownames(combined@meta.data) %in% colnames(this_obj),
           this_ct,
           combined@meta.data$tmp_ct)
  library(tidyverse)
  
  Idents(combined) <- combined$tmp_ct
  custom_color <- c('#C0C0C0', '#B00D23')
  
  # pct proportion
}


Idents(combined) <- as.factor(combined$tmp_ct)
custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]



DefaultAssay(combined) <- "RNA"
combined <- ScaleData(combined)

levels(Idents(combined))
heat_obj <-
  subset(
    x = combined,
    idents = c(
      "Cardiac mesoderm",
      "SHF progenitor",
      "FHF progenitor",
      "Epicardial progenitor",
      "Atrial cardiomyocytes",
      "Ventricular cardiomyocytes",
      "Pacemaker cells",
      "Vascular smooth muscle cells",
      "Cardiac fibroblast"
    )
  )

Idents(heat_obj) <- as.factor(heat_obj$tmp_ct)

```

## Top 5 degs

```{r}

this_samples <- c("N1KO2", "NIKO10", "Con30","N1KO14","N1KO30")

this_idents = c(
  "Cardiac mesoderm",
  "SHF progenitor",
  "FHF progenitor",
  "Epicardial progenitor",
  "Atrial cardiomyocytes",
  "Ventricular cardiomyocytes",
  "Pacemaker cells",
  "Vascular smooth muscle cells",
  "Cardiac fibroblast"
)
  

provided_marker <- provided_marker %>%
  arrange(cell_type) %>%
  filter(cell_type %in% this_idents)


this_genes <- provided_marker$gene
#
#this_markers <- FindAllMarkers(heat_obj, logfc.threshold = 0.4, min.pct = 0.5)
#
#this_genes <- this_markers %>% 
#  arrange(desc(avg_log2FC)) %>%
#  group_by(cluster) %>%
#  top_n(5, avg_log2FC) %>%
#  arrange(cluster) %>%
#  pull(gene) %>%
#  unique()

```

```{r}

new_ident <- as.factor(heat_obj$tmp_ct)
heat_obj <- AddMetaData(heat_obj, new_ident, col.name = "heatmap_ident")
Idents(heat_obj) <- heat_obj$heatmap_ident

p3 <-
  DoHeatmap(
    object = heat_obj,
    features = this_genes,
    group.colors = brewer.pal(8, "RdYlBu"),
    angle = 30,
    size = 6
  ) + scale_fill_gradientn(colors = c("#4575b4", "white", "#d73027")) + 
    theme(text = element_text(size = 20)) + 
  NoLegend() 

n1 <- length(unique(tst$gn))
n2 <- length(unique(tst$smpl))

library(Scillus)

png(paste0("heat1.png"),
    width = 4000,
    height = 4000,
    res = 300)

print(p3)
dev.off()

p4 <- plot_heatmap(dataset = heat_obj, 
              markers = this_genes,
              sort_var = c("tmp_ct"),
              anno_var = c("tmp_ct"),
              anno_colors = list("Set2"))

png(paste0("heat2.png"),
    width = 2500,
    height = 2000,
    res = 300)

print(p4)
dev.off()


p5 <-
  DotPlot(heat_obj,
          assay = "RNA",
          features = unique(this_genes),
          cols = c('#C0C0C0', '#B00D23'),
          group.by = "heatmap_ident") + theme(axis.text.x = element_text(angle = 30, hjust =
                                                                              1))

png(paste0("dotplot_selected.png"),
    width = 4000,
    height = 2000,
    res = 300)

print(p5)
dev.off()



provided_marker <- read.csv("provided_marker_manual.csv", header = T)


provided_marker$cell_type <- as.factor(provided_marker$cell_type)
provided_marker <- provided_marker %>%
  arrange(cell_type) 


this_genes <- provided_marker$gene
heat_obj2 <-
  subset(
    x = combined,
    idents = c(
      "other"
    ),invert=T
  )

p6 <-
  DotPlot(heat_obj2,
          assay = "RNA",
          features = unique(this_genes),
          cols = c('#C0C0C0', '#B00D23'),
          group.by = "tmp_ct") + theme(axis.text.x = element_text(angle = 30, hjust =
                                                                              1))

png(paste0("dotplot_all.png"),
    width = 5000,
    height = 2000,
    res = 300)

print(p6)
dev.off()

```
