---
title: "Cell proportion"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)
library(fgsea)
library(msigdbr)
library(monocle3)
library(batchelor)
library(Matrix.utils)
library(data.table)
#BiocManager::install(c('batchelor', 'Matrix.utils'))
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}
here::i_am("7_GSEA.Rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}
source("functions.R")
####

#combined <- readRDS("combined.rds")
combined <- qs::qread('combined.qsave')
####

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$seurat_clusters
custom_color <-
  as.character(palette36.colors(36)[-2])[1:length(levels(Idents(combined)))]


provided_marker <- read.csv("provided_marker_manual.csv", header = T)


provided_marker$cell_type <- as.factor(provided_marker$cell_type)

Idents(combined) <- combined$orig.ident
DefaultAssay(combined) <- "RNA"
i = 1
j = 1
k = 1

empty_category <- as.factor(combined$orig.ident)
levels(empty_category) <-
  rep("empty_category", length(levels(empty_category)))
combined <-
  AddMetaData(combined, metadata = empty_category, col.name = "empty_category")

```

# GSEA


```{r,echo=F,eval=F,message=FALSE,warning=F}

all_gene_sets = msigdbr(species = "human")
this_terms <- all_gene_sets %>%
  filter(gs_name == 'REACTOME_SIGNALING_BY_NOTCH'
         | gs_name == 'REACTOME_SIGNALING_BY_NOTCH1'
         | gs_name == 'GOBP_NOTCH_SIGNALING_INVOLVED_IN_HEART_DEVELOPMENT'
         | gs_name == 'BIOCARTA_NOTCH_PATHWAY'
         | gs_name == 'BIOCARTA_WNT_PATHWAY'
         | gs_name == 'GOBP_CANONICAL_WNT_SIGNALING_PATHWAY_INVOLVED_IN_HEART_DEVELOPMENT'
         | gs_name == 'GOBP_CANONICAL_WNT_SIGNALING_PATHWAY_INVOLVED_IN_REGULATION_OF_CELL_PROLIFERATION'
         | gs_name == 'GOBP_NEGATIVE_REGULATION_OF_WNT_SIGNALING_PATHWAY_INVOLVED_IN_HEART_DEVELOPMENT'
         | gs_name == 'GOBP_REGULATION_OF_WNT_SIGNALING_PATHWAY_INVOLVED_IN_HEART_DEVELOPMENT'
         | gs_name == 'GOBP_WNT_SIGNALING_PATHWAY_INVOLVED_IN_HEART_DEVELOPMENT'
         | gs_name == 'GOBP_HIPPO_SIGNALING'
         | gs_name == 'GOBP_NEGATIVE_REGULATION_OF_HIPPO_SIGNALING'
         | gs_name == 'GOBP_POSITIVE_REGULATION_OF_HIPPO_SIGNALING'
         | gs_name == 'REACTOME_SIGNALING_BY_HIPPO'
         | gs_name == 'WP_MECHANOREGULATION_AND_PATHOLOGY_OF_YAPTAZ_VIA_HIPPO_AND_NONHIPPO_MECHANISMS'
         )

m_list = this_terms %>% split(x = .$gene_symbol, f = .$gs_name)

```


```{r,echo=F,eval=F,message=FALSE,warning=F}
#all_dirs <- list.dirs("C:/Users/flyku/Documents/GitHub/NOTCH1-scRNAseq/result_07212021/deg/", recursive = F)
all_dirs <- list.dirs("C:/Users/flyku/Documents/GitHub/NOTCH1-scRNAseq/result/deg/", recursive = F)



i = 1
for (i in 1:length(all_dirs)) {
  this_dir <- all_dirs[i]
  print(i)
  deg_path <- paste0(this_dir, "/deg_full.csv")
  if (file.exists(deg_path)) {
    this_deg <- read.csv(deg_path)
    dir.create(paste0(this_dir, "/selected_terms"))
    if (nrow(this_deg) > 20) {
      res <- this_deg %>%
        dplyr::select(gene, avg_log2FC) %>%
        arrange(desc(avg_log2FC)) %>%
        na.omit() %>%
        distinct() %>%
        group_by(gene) %>%
        deframe() %>%
        sort(decreasing = T)
      
      
      fgseaRes <- fgsea(pathways = m_list,
                        stats = res,
                        nperm = 1000)
      fgseaResTidy <- fgseaRes %>%
        as_tibble() %>%
        arrange(desc(NES)) %>%
        dplyr::select(-ES,-nMoreExtreme) %>%
        arrange(padj) %>%
        fwrite(
          file = paste0(this_dir,
                        "/selected_terms/selected_terms.csv"),
          sep = ",",
          sep2 = c("", " ", "")
        )
      j = 2
      
      for (j in 1:length(m_list)) {
        plot1 <-
          plotEnrichment(m_list[[j]],
                         res) + ggplot2::labs(title = names(m_list)[j])
        if (nrow(plot1$data) > 3) {
          png(
            paste0(
              this_dir,
              "/selected_terms/",
              names(m_list[j]),
              ".png"
            ),
            width = 1500,
            height = 1000,
            res = 300
          )
          print(plot1)
          dev.off()
        }
      }
      docs <- list.files(
        paste0(this_dir,
               "/selected_terms/"),
        pattern = "*.png",
        full.names = T
      )
      
      # Use file.size() immediate, instead of file.info(docs)$size:
      inds <- file.size(docs) < 2000
      
      # Remove all documents with file.size = 1 from the directory
      file.remove(docs[inds])
    }
  }
  
}

```
