---
title: "Figures: UMAP cell type, expression, violin"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
    code_folding: hide
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = T)
knitr::opts_chunk$set(message = F)
knitr::opts_chunk$set(warning = F)
knitr::opts_chunk$set(error = F)
knitr::opts_chunk$set(fig.width = 8)

library(Seurat)
library(cowplot)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(RColorBrewer)
library(tidyverse)

```


# Set working dir

```{r,,eval=T,message=F,warning=F,error=F}

here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r}
source("functions.R")
dir.create('../sample_obj', showWarnings = F)
combined <- qs::qread('combined.qsave')

DefaultAssay(combined) <- "RNA"
Idents(combined) <- combined$orig.ident

sample_color <-
  as.character(glasbey.colors()[-1])

cell_type_color <-
  as.character(palette36.colors(36)[-2])
two_color <- c('#C0C0C0', '#B00D23')


provided_marker <- read_csv("../marker/marker_by_day.csv") %>%
  mutate(cell_type = factor(cell_type))

provided_marker

t1 = data.frame(v1=levels(as.factor(combined$cell_type)), v2=cell_type_color[1:14])

Idents(combined)

tmp_ident <- as.factor(combined$orig.ident)

levels(tmp_ident) <-
  c(
    "WT D0",
    "WT D2",
    "WT D5",
    "WT D10",
    "WT D14",
    "WT D30",
    "N1KO D0",
    "N1KO D2",
    "N1KO D5",
    "N1KO D10",
    "N1KO D14",
    "N1KO D30"
  )

combined <- AddMetaData(combined, tmp_ident, col.name = "sample")

#qs::qsave(combined, "combined.qsave")

```


```{r, fig.width=10, fig.height=8}
Idents(combined) <- combined$sample

p1 <- DimPlot(
  combined,
  reduction = "umap",
  cols = sample_color,
  label = F,
  pt.size = 0.1,
  repel = T,
  label.box = F
) + coord_fixed(0.8)

pdf("../figure/umap_sample.pdf",width = 12, height = 8)
print(p1)
dev.off()


p1 <- DimPlot(
  combined,
  group.by = "cell_type",
  reduction = "umap",
  cols = cell_type_color,
  label = F,
  pt.size = 0.1,
  repel = T,
  label.box = F
) + coord_fixed(0.8)

pdf("../figure/umap_cell_type.pdf",width = 12, height = 8)
print(p1)
dev.off()

```

# Setup

```{r}
all_ct <- levels(as.factor(combined$cell_type))
all_cell_type_cols <- cell_type_color[1:length(all_ct)]
names(all_cell_type_cols) <- all_ct

all_samples <- levels(as.factor(combined$orig.ident))
all_sample_cols <- sample_color[1:length(all_samples)]
names(all_sample_cols) <- all_samples

print(all_cell_type_cols)
print(all_sample_cols)
print(two_color)

```

```{r, include=F}

print_pie <- function(this_sample_name = "Con2") {
  Idents(this_combined) <- this_combined$cell_type
  
  this_cols <- all_cell_type_cols[as.character(unique(this_combined$cell_type))]
  pie_df <- table(as.factor(this_combined$cell_type))
  pct <- round(100 * pie_df / sum(pie_df))
  
  this_cols <- this_cols[names(pct)]
  pdf(paste0("../figure/pie_",this_sample_name,".pdf"), width = 8, height = 5)
  print(pie(pie_df,
            labels = paste(sep = " ", pct, "%"),
            col = this_cols))
  dev.off()
}

print_umap_day <- function(this_sample_name = "day30", coords = 0.8) {
  Idents(this_combined) <- this_combined$cell_type
  
  this_cols <- all_cell_type_cols[as.character(unique(this_combined$cell_type))]
  
  p2 <-
    DimPlot(
      this_combined,
      split.by = "orig.ident",
      reduction = "umap",
      cols = this_cols,
      pt.size = 0.2
    ) + coord_fixed(coords)
  
  pdf(paste0("../figure/umap_",this_sample_name,".pdf"), width = 12, height = 5)
  print(p2)
  dev.off()
  
}


print_genes <-
  function(this_sample_name,
           genes = c("TNNT2", "DDR2"),
           width = 10,
           height = 6,
           coords = 1) {
    p1 <-
      FeaturePlot(
        this_combined,
        features = genes,
        ncol = 2,
        keep.scale = NULL,
        pt.size = 0.25,
        cols = two_color,
        order = T
      ) + coord_fixed(coords)
    
    
    pdf(paste0("../figure/genes_", this_sample_name, ".pdf"),
        width = width,
        height = height)
    
    print(p1)
    dev.off()
  }

print_genes_day <-
  function(this_sample_name,
           genes = c("TNNT2", "DDR2"),
           width = 10,
           height = 6,
           coords = 1) {
    p1 <-
      FeaturePlot(
        this_combined,
        features = genes,
        ncol = 2,
        split.by = "orig.ident",
        keep.scale = NULL,
        pt.size = 0.25,
        cols = two_color,
        order = T
      ) & coord_fixed(coords) & theme(legend.position = "left")
    
    pdf(paste0("../figure/genes_", this_sample_name, ".pdf"),
        width = width,
        height = height)
    
    print(p1)
    dev.off()
  }

print_violin_day <-
  function(this_sample_name,
           genes = c("TNNT2", "MYL2"),
           width = 8,
           height = 6) {
    this_cols <- all_sample_cols[as.character(unique(this_combined$orig.ident))]
    p1 <-
      VlnPlot(
        this_combined,
        features = genes,
        split.by = "orig.ident",
        pt.size = 0.1,
        cols = this_cols
      ) & coord_fixed(0.61) & theme(legend.position = "left")
    
    
    pdf(paste0("../figure/violin_", this_sample_name, ".pdf"),
        width = width,
        height = height)
    
    print(p1)
    dev.off()
  }


```

# Pie chart

```{r}
this_samples <- levels(as.factor(combined$orig.ident))
i <- this_samples[4]
for(i in this_samples) {
  this_sample_path <- paste0("../sample_obj/",i,".qsave")
  this_combined <- qs::qread(this_sample_path)
  print_pie(i)
}

```

# Day0

```{r}

this_combined <- qs::qread("../integration/day0_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day0", coords = 1.2)


```

# Day2

```{r}
this_sample_name <- "day2"
this_combined <- qs::qread("../integration/day2_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day2")
print_genes_day("day2", genes = c("MIXL1"))

print_violin_day("day2", genes = c("MIXL1"))
```

# Day5

```{r}
this_combined <- qs::qread("../integration/day5_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day5")
print_genes_day("day5", genes = c("ISL1"), coords = 0.8)
print_violin_day("day5", genes = c("ISL1"))
```

# Day10

```{r}
this_combined <- qs::qread("../integration/day10_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day10")
print_genes_day("day10", genes = c("ISL1","NKX2-5"), coords = 0.8)

```

# Day14

```{r}
this_combined <- qs::qread("../integration/day14_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day14")
print_genes_day("day14", genes = c("TNNT2", "DDR2"))
print_violin_day("day14", genes = c("TNNT2", "DDR2"))
```


# Day30

```{r}
this_combined <- qs::qread("../integration/day30_harmony.qsave")
Idents(this_combined) <- this_combined$cell_type
print_umap_day("day30")
print_genes_day("day30", genes = c("TNNT2", "MYL2"))
print_violin_day("day30", genes = c("TNNT2", "MYL2"))
```

# Con30

```{r}

Idents(this_combined) <- this_combined$cell_type
p2 <-
  DimPlot(
    this_combined,
    reduction = "umap",
    cols = cell_type_color,
    pt.size = 0.2
  ) + coord_fixed(1)

pdf("umap_Con30.pdf", width = 6, height = 5)
print(p2)
dev.off()


pie_df <- table(as.factor(this_combined$cell_type))
pct <- round(100 * pie_df / sum(pie_df))

pdf("pie_Con30.pdf", width = 8, height = 5)
print(pie(
  pie_df,
  labels = paste( sep = " ", pct, "%"),
  col = cell_type_color
))
dev.off()

Idents(combined) <- combined$cell_type


p3 <-
  FeaturePlot(
    this_combined,
    features = c("TNNT2","MYL2"),
    ncol = 2,
    keep.scale = NULL,
    pt.size = 0.25,
    cols = two_color
  ) + coord_fixed(1)

pdf("feature_Con30.pdf", width = 10, height = 6)

print(p3)
dev.off()

```


# N1KO30

```{r}
this_combined <- qs::qread("../integration/day30_harmony.qsave")

Idents(this_combined) <- this_combined$cell_type
p2 <-
  DimPlot(
    this_combined,
    reduction = "umap",
    cols = cell_type_color,
    pt.size = 0.2
  ) + coord_fixed(1)

pdf("umap_N1KO30.pdf", width = 6, height = 5)
print(p2)
dev.off()


pie_df <- table(as.factor(this_combined$cell_type))
pct <- round(100 * pie_df / sum(pie_df))

pdf("pie_N1KO30.pdf", width = 8, height = 5)
print(pie(
  pie_df,
  labels = paste( sep = " ", pct, "%"),
  col = cell_type_color
))
dev.off()

Idents(combined) <- combined$cell_type


p3 <-
  FeaturePlot(
    this_combined,
    features = c("TNNT2","MYL2"),
    ncol = 2,
    keep.scale = NULL,
    pt.size = 0.25,
    cols = two_color
  ) + coord_fixed(1)

pdf("feature_N1KO30.pdf", width = 10, height = 6)

print(p3)
dev.off()

```



