---
title: "Data integration by days"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(harmony)
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::i_am("integration_day.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combined <- qs::qread('combined.qsave')



```

# Dimension reduction

```{r}
dir.create("../integration")

# Harmony integration method
days <- c("5", "8", "10", "14")
combine.list <- SplitObject(combined, split.by = "sample")

i = "10"
Idents(combined) <- combined$sample
for(i in days) {
  this_days <- c(paste0("HG Day", i), paste0("Control Day", i))
  sample_idx <- which(names(combine.list) %in% this_days)
  sub_list <- combine.list[sample_idx]
  sub_combined <-
    merge(sub_list[[1]], y=c(sub_list[[2]]))
  
  DefaultAssay(sub_combined) <- "RNA"
  sub_combined <- NormalizeData(sub_combined)
  sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  sub_combined <- FindVariableFeatures(sub_combined, selection.method = "vst", nfeatures = 2000) 
  sub_combined <- RunPCA(sub_combined, pc.genes = sub_combined@var.genes, npcs = 20, verbose = FALSE)
  sub_combined <- RunHarmony(sub_combined, "orig.ident", plot_convergence = FALSE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "harmony", dims = 1:20)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "harmony", dims = 1:20)
  sub_combined <- FindClusters(sub_combined, resolution = 0.2)
  
  DefaultAssay(sub_combined) <- "RNA"
  Idents(sub_combined) <- sub_combined$sample
  #this_combind <- subset(combined, idents = this_days)
  #sub_combined <-
  #  AddMetaData(sub_combined, this_combind$cell_type, col.name = "cell_type")
  qs::qsave(sub_combined, paste0("../integration/day", i, "_harmony.qsave"))
}

```


# Session info

```{r,echo=F,eval=T,message=F,warning=F}
sessionInfo()
```
