---
title: "Preprocess each sample"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(harmony)
```


# Set working dir

```{r,echo=F,eval=T,message=F,warning=F,error=F}

here::i_am("process_sample.rmd")
here::set_here()
print(paste("Current working directory:", here::here()))

```

# Load data

```{r,echo=F,eval=T,message=F,warning=F,error=F}

combined <- qs::qread('combined.qsave')

table(combined$sample)
```

# Dimension reduction

```{r}
dir.create("../sample_obj")

sample_list <- levels(combined$sample)

i = 1
i = 8
Idents(combined) <- combined$sample
for(i in 1:8) {
  this_sample_name <- sample_list[i]
  sub_combined <- subset(combined, idents = this_sample_name)
  this_day <- sub(".* ", "", this_sample_name)
  #this_day <- this_sample_name
  old_obj <- qs::qread(paste0("../sample_obj/", this_day, "_cell_type.qsave"))
  old_obj <- old_obj[,colnames(sub_combined)]
  old_cell_type <- old_obj$cell_type
  
  DefaultAssay(sub_combined) <- "RNA"
  sub_combined <- NormalizeData(sub_combined)
  sub_combined <- ScaleData(sub_combined, verbose = FALSE)
  sub_combined <- FindVariableFeatures(sub_combined, selection.method = "vst", nfeatures = 2000) 
  sub_combined <- RunPCA(sub_combined, pc.genes = sub_combined@var.genes, npcs = 20, verbose = FALSE)
  sub_combined <-
    RunUMAP(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <-
    FindNeighbors(sub_combined, reduction = "pca", dims = 1:20)
  sub_combined <- FindClusters(sub_combined, resolution = 0.2)
  
  DefaultAssay(sub_combined) <- "RNA"
  Idents(sub_combined) <- sub_combined$sample
  sub_combined <- AddMetaData(sub_combined, old_cell_type, col.name = "old_cell_type")
  qs::qsave(sub_combined, paste0("../sample_obj/", this_sample_name, "_processed.qsave"))
}

```


```{r,echo=F,eval=T,message=F,warning=F}

table(sub_combined$orig.ident)

DimPlot(
  sub_combined,
  reduction = "umap",
  group.by = "old_cell_type",
  label = T,
  pt.size = 0.5
)


FeaturePlot(
  sub_combined,
  reduction = "umap",
  features = "TNNT2",
  pt.size = 0.5
)

FeaturePlot(
  sub_combined,
  reduction = "umap",
  features = "NKX2-5",
  pt.size = 0.5
)

FeaturePlot(
  sub_combined,
  reduction = "umap",
  features = "TNNT2",
  pt.size = 0.5
)


obj1 <- qread("../sample_obj/HG Day5_processed.qsave")
obj2 <- qread("../sample_obj/HG Day8_processed.qsave")
obj3 <- qread("../sample_obj/HG Day10_processed.qsave")
obj4 <- qread("../sample_obj/HG Day14_processed.qsave")
obj5 <- qread("../sample_obj/Control Day5_processed.qsave")
obj6 <- qread("../sample_obj/Control Day8_processed.qsave")
obj7 <- qread("../sample_obj/Control Day10_processed.qsave")
obj8 <- qread("../sample_obj/Control Day14_processed.qsave")

combined_qc <-
  merge(
    x = obj1,
    y = c(obj2,
          obj3,
          obj4,
          obj5,
          obj6,
          obj7,
          obj8)
  )

combined_qc <-
  subset(
    combined_qc,
    subset =
      nFeature_RNA < 7000 &
      nCount_RNA < 30000 &
      percent.ribo < 50 &
      percent.mito < 20
  )


combined_qc <- NormalizeData(combined_qc, verbose = FALSE)
combined_qc <- FindVariableFeatures(combined_qc, verbose = FALSE)
combined_qc <- ScaleData(combined_qc, verbose = FALSE)
combined_qc <- RunPCA(combined_qc, npcs = 20, verbose = FALSE)
combined_qc <- RunUMAP(combined_qc, reduction = "pca", dims = 1:20, verbose = FALSE)
combined_qc <- FindNeighbors(combined_qc, reduction = "pca", dims = 1:20, verbose = FALSE)
combined_qc <- FindClusters(combined_qc, resolution = 0.2, verbose = FALSE)

qs::qsave(combined_qc, paste0("./combined.qsave"))


sessionInfo()
```
