---
title: "Differential gene expression analysis"
author: "Cankun Wang"
date: "`r format(Sys.time(), '%m/%d/%Y')`"
output: 
  html_document:
    toc: true
    toc_float: true
    number_sections: true
    df_print: paged
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)
knitr::opts_chunk$set(error = FALSE)
library(Seurat)
library(cowplot)
library(dplyr)
library(ggplot2)
library(patchwork)
library(here)
library(qs)
library(Polychrome)
library(tidyverse)
library(enrichR)
```

```{r}


combined <- qs::qread('combined.qsave')


# Note: remember to use the correct species
dbs <-
  c(
    "GO_Molecular_Function_2018",
    "GO_Cellular_Component_2018",
    "GO_Biological_Process_2018",
    "KEGG_2019_Human"
  )

source("../common/functions.R")


# Select the RNA counts slot to be the default assay
DefaultAssay(combined) <- "RNA"

Idents(combined) <- combined$orig.ident
levels(Idents(combined))
```

# DEG: stim vs ctrl by each cell type

```{r}
DefaultAssay(combined) <- "RNA"
dir.create("./result")
dir.create(paste0("./result/deg"))
dir.create(paste0("./result/deg/stim_vs_ctrl"))

Idents(combined) <- combined$orig.ident

this_clusters <- levels(as.factor(combined$cell_type))

i = 1
ident1 <- "stim_raw_feature_bc_matrix"
ident2 <- "ctrl_raw_feature_bc_matrix"
comparison_name <- "stim_vs_ctrl"


for (i in seq_along(this_clusters)) {
  this_cluster <- this_clusters[i]
  
  Idents(combined) <- combined$cell_type
  this_combined <-
    subset(combined, ident = this_cluster)
  
  Idents(this_combined) <- this_combined$orig.ident
  DefaultAssay(this_combined) <- "RNA"
  
  
  dir.create(paste0("./result/deg/",
                    comparison_name,
                    "/",
                    this_cluster))
  
  RESULT_DIR <-
    paste0(paste0("./result/deg/",
                  comparison_name,
                  "/",
                  this_cluster,
                  "/"))
  
  cts_markers <-
    FindMarkers(this_combined,
                ident.1 = ident1,
                ident.2 = ident2) %>%
    rownames_to_column("gene") %>%
    filter(p_val_adj < 0.05) %>%
    write_csv(paste0(RESULT_DIR, "deg.csv"))
  
  this_up <- cts_markers %>%
    filter(avg_log2FC > 0) %>%
    pull(gene)
  this_down <- cts_markers %>%
    filter(avg_log2FC < 0) %>%
    pull(gene)
  
  ### UP
  if (length(this_up) > 10) {
    enriched_combined <- enrichr(this_up, dbs)
    enriched_combined <- lapply(enriched_combined, function(x) {
      x$Overlap <- paste0(" ", x$Overlap)
      return(x[, c(-5,-6)])
    })
    
    write.csv(
      enriched_combined$GO_Molecular_Function_2018,
      paste0(RESULT_DIR, "GO_MF_up.csv")
    )
    write.csv(
      enriched_combined$GO_Cellular_Component_2018,
      paste0(RESULT_DIR, "GO_CC_up.csv")
    )
    write.csv(
      enriched_combined$GO_Biological_Process_2018,
      paste0(RESULT_DIR, "GO_BP_up.csv")
    )
    write.csv(enriched_combined$KEGG_2019_Human,
              paste0(RESULT_DIR, "KEGG_up.csv"))
  }
  ### DOWN
  if (length(this_down) > 10) {
    enriched_combined <- enrichr(this_down, dbs)
    enriched_combined <- lapply(enriched_combined, function(x) {
      x$Overlap <- paste0(" ", x$Overlap)
      return(x[, c(-5,-6)])
    })
    
    write.csv(
      enriched_combined$GO_Molecular_Function_2018,
      paste0(RESULT_DIR, "GO_MF_down.csv")
    )
    write.csv(
      enriched_combined$GO_Cellular_Component_2018,
      paste0(RESULT_DIR, "GO_CC_down.csv")
    )
    write.csv(
      enriched_combined$GO_Biological_Process_2018,
      paste0(RESULT_DIR, "GO_BP_down.csv")
    )
    write.csv(enriched_combined$KEGG_2019_Human,
              paste0(RESULT_DIR, "KEGG_down.csv"))
    
  }
}


```



# Cell type specific genes

```{r}
DefaultAssay(combined) <- "RNA"
dir.create(paste0("./result/deg"))
dir.create(paste0("./result/deg/cell_type_specific_genes"))

Idents(combined) <- combined$cell_type

# 30 mins
cts_markers <- FindAllMarkers(combined)

cts_markers %>%
  write.csv("./result/deg/cell_type_specific_genes/cluster_specific_genes_combined.csv")

i = 1
for (i in seq_along(levels(cts_markers$cluster))) {
  this_cluster <- levels(cts_markers$cluster)[i]
  dir.create(paste0("./result/deg/cell_type_specific_genes/",this_cluster))
  cts_markers %>%
    filter(cluster == this_cluster) %>%
    write_csv(paste0("./result/deg/cell_type_specific_genes/",this_cluster,"/cell_type_specific_genes.csv"))
}

```

